### ISSUE TITLE
[bug] ChunkLoadError happening on a NextJS app using rainbowkit

### ISSUE THREAD

**Issue by moaazsidat** [rainbow-me/rainbowkit#1374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.5

### Current Behavior

We're running into ChunkLoadError on NextJS, with stack traces pointing to rainbowkit after upgrading rainbowkit from `1.0.1` to `1.0.4`

Seeing an error like so:
```
Loading chunk 6599 failed.
(timeout: <our_domain>/_next/static/chunks/6599.357b8ebeee072ee8.js)
```

### Expected Behavior

We're using the recommended rainbowkit setup for NextJS webpack config resolution

```
webpack(config) {
    config.resolve.fallback = { fs: false, net: false, tls: false }
    return config
  },
```

and in our `_app.tsx`, using the recommended setup from rainbowkit docs as well

```

const { chains, publicClient } = configureChains(...)

const { connectors } = getDefaultWallets({
  appName: '<project_name>',
  projectId: '<project_id>',
  chains,
})

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
})

function MyApp({ Component, pageProps }: AppProps) {
  return (
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider coolMode chains={chains}>
            <Component {...pageProps} />
          </RainbowKitProvider>
        </WagmiConfig>
  )
}

```

### Anything else?

Any help would be much appreciated!

**Comment by DanielSinclair** [comment]
@moaazsidat Can you share a reproducible example on CodeSandbox? Can you also share the full stack trace and error logs?

**Comment by moaazsidat** [comment]
@DanielSinclair Have not been able to reliably reproduce it, have mostly just seeing it get triggered it via our Sentry logs on our frontend NextJS app

Full stack trace: 

```
ChunkLoadError: Loading chunk 6599 failed.
(timeout: https://ethglobal.com/_next/static/chunks/6599.357b8ebeee072ee8.js)
  at (timeout: (/_next/static/chunks/6599.357b8ebeee072ee8.js))
  at __webpack_require__.f.j(webpack://_N_E/webpack/runtime/jsonp chunk loading:27:1)
  at reduce(webpack://_N_E/webpack/runtime/ensure chunk:6:1)
  at Array.reduce(<anonymous>)
  at __webpack_require__.e(webpack://_N_E/webpack/runtime/ensure chunk:5:1)
  at initProvider_fn(./node_modules/@wagmi/core/node_modules/@wagmi/connectors/dist/walletConnect.js:225:73)
  at createProvider_fn(./node_modules/@wagmi/core/node_modules/@wagmi/connectors/dist/walletConnect.js:219:61)
  at new WalletConnectConnector(./node_modules/@wagmi/core/node_modules/@wagmi/connectors/dist/walletConnect.js:65:20)
  at createConnector(./node_modules/@rainbow-me/rainbowkit/dist/index.js:275:71)
  at getWalletConnectConnector(./node_modules/@rainbow-me/rainbowkit/dist/index.js:300:1)
  at <object>.createConnector(./node_modules/@rainbow-me/rainbowkit/dist/index.js:508:1)
  at forEach(./node_modules/@rainbow-me/rainbowkit/dist/index.js:96:49)
  at Array.forEach(<anonymous>)
  at connectors(./node_modules/@rainbow-me/rainbowkit/dist/index.js:73:1)
  at new Config(./node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js:398:1)
  at createConfig(./node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js:636:1)
  at createConfig(./node_modules/wagmi/dist/index.js:37:18)
  at call(./src/pages/_app.tsx:56:21)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:1)
  at execute(webpack://_N_E/:5:16)
  at <anonymous>(./node_modules/next/dist/client/route-loader.js:230:51)
```

**Comment by DanielSinclair** [comment]
Odd. It looks like the issue is appearing beyond the RainbowKit scope and somewhere upstream in the WalletConnect libraries, and that would make sense if this only began appearing once we rolled over WalletConnect v2. Will relay to the WalletConnect team and see if they've seen similar bundler issues.

**Comment by moaazsidat** [comment]
@DanielSinclair any updates on this issue? or a linked issue on WalletConnect?

**Comment by glitch-txs** [comment]
Hi, could you share a minimal reproducible example?

**Comment by glitch-txs** [comment]
hey @moaazsidat feel free to open an issue on our [monorepo](https://github.com/WalletConnect/walletconnect-monorepo). First time seeing it tbh

**Comment by DanielSinclair** [comment]
Closing for inactivity. Let me know if this is still occurring for you with the latest version of Wagmi and RainbowKit.
