### ISSUE TITLE
[bug] Got "No matching key, history: 1662323434234" while disconnecting after refresh the page using wallet connect

### ISSUE THREAD

**Issue by jingxuan98** [rainbow-me/rainbowkit#1382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.4

### Current Behavior

After connecting via WalletConnect & refreshing the page, it throws this error when i try to disconnect
<img width="800" alt="Screenshot 2023-07-07 at 6 59 12 PM" src="https://github.com/rainbow-me/rainbowkit/assets/43902263/a3957c11-6417-44de-8c50-b86ccba7d2c3">

Able to disconnect before refreshing the page

Any idea to at least catch this error and handle it softly? i tried using a try catch when calling the disconnect() but the page still crashes

### Expected Behavior

Able to disconnect without throwing an error

### Steps To Reproduce

1. Connect via WalletConnect
2. Refresh the page
3. Disconnect after refresh

**Comment by moaazsidat** [comment]
Running into this as well 

Also running into `No matching key. keychain <some alphanumeric value here>`
Full stack trace:
```
Error: No matching key. keychain: <some alphanumeric value here>
  at this.get(./node_modules/@walletconnect/core/dist/index.es.js:1:16678)
  at this.decode(./node_modules/@walletconnect/core/dist/index.es.js:1:18736)
  at this.decode(./node_modules/@walletconnect/core/dist/index.es.js:1:18798)
  at <anonymous>(./node_modules/@walletconnect/core/dist/index.es.js:1:47319)
  at ReflectApply(./node_modules/@walletconnect/core/dist/index.es.js:1:47537)
  at EventEmitter.prototype.emit(./node_modules/events/events.js:158:1)
  at index_es_Ot.onMessageEvent(./node_modules/@walletconnect/core/dist/index.es.js:1:36928)
```

This seems to be coming from WalletConnect, but more specifically it seems to be caused by how `@walletconnect/ethereum-provider` is used (based on [this comment](https://github.com/WalletConnect/walletconnect-monorepo/issues/2326#issuecomment-1604967391))?

**Comment by DanielSinclair** [comment]
The latest version of Wagmi includes upgraded versions of WalletConnect that seem to be more stable. Let me know if you're still seeing this problem.

**Comment by jingxuan98** [comment]
Yes @DanielSinclair , still getting this issue with latest rainbowkit 1.0,7 and wagmi 1.3.9
![Screenshot 2023-07-21 at 10 35 34 AM](https://github.com/rainbow-me/rainbowkit/assets/43902263/37cc079b-fb6b-47b8-b3d4-4c87e3c77f55)

**Comment by Bhupesh-mfsi** [comment]
> Yes @DanielSinclair , still getting this issue with latest rainbowkit 1.0,7 and wagmi 1.3.9 ![Screenshot 2023-07-21 at 10 35 34 AM](https://user-images.githubusercontent.com/43902263/255057321-37cc079b-fb6b-47b8-b3d4-4c87e3c77f55.png)

I am also getting same error with latest version

**Comment by Bhupesh-mfsi** [comment]
> 

I tried clearing my local storage of react app and it worked for me.

**Comment by lunarinlunarinlunarin** [comment]
are there any updates on this issue? if not could some one tell me where I could at least catch the error?

**Comment by deepak-interakt** [comment]
facing same issues aswell ! any update on this ?

**Comment by fodisi** [comment]
same error here w/ the latest
```
"@rainbow-me/rainbowkit": "^1.0.8",
"wagmi": "^1.3.10"
```

**Comment by glitch-txs** [comment]
Hi everyone this was discussed [here](https://github.com/orgs/WalletConnect/discussions/3291). And it seems to be an issue related to the wallet implementation side.
