### ISSUE TITLE
[bug] Uncaught TypeError in React JS (CRA) prod build

### ISSUE THREAD

**Issue by arsen39** [rainbow-me/rainbowkit#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.9

### wagmi Version

1.3.10

### Current Behavior

I've encountered an unusual issue (at least for me) on one of my commercial projects. Due to an NDA, I won't delve into the details, but the essential information is that the project is built with React and uses JS. We decided to integrate RainbowKit as a universal tool for wallet connections. During local development and integration of RainbowKit, everything functioned seamlessly without any issues. However, when compiling the production build, I consistently receive the following error:

`Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at 59103 (number.ts:1:24)
    at n (bootstrap:19:32)
    at 94069 (index.ts:340:1)
    at n (bootstrap:19:32)
    at 43291 (index.ts:1:1)
    at n (bootstrap:19:32)
    at 38641 (sdk.ts:5:1)
    at n (bootstrap:19:32)
    at 16056 (index.ts:1:1)`
    
    
![image](https://github.com/rainbow-me/rainbowkit/assets/74368493/2c40b5fd-b6ee-489f-8b13-abdcad294664)

This error persists regardless of whether I build locally and upload to the server, run it locally, or directly build on the AWS server. The outcome remains consistent: the same error appears, and the project fails to launch.

Suspecting potential conflicts with dependencies, especially given the project's scale, I tested this by creating a fresh CRA project in JS. I set up all dependencies in alignment with your CodeSandbox project but opted for a JS-based CRA instead of TypeScript. The result was consistent: while 'npm start' ran smoothly, launching the build after 'npm run build' triggered the aforementioned error.

I attempted to install 'wagmi' and 'viem' of the same versions and run them without RainbowKit, following their respective documentation. No error surfaced. This leads me to surmise that the issue arises when adding RainbowKit's **connectors** to the wagmi configuration object:

`const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  projectId: process.env.REACT_APP_WALLET_CONNECT_PROJECT_ID,
  chains
});`

`const config = createConfig({
  publicClient,
  webSocketPublicClient,
  connectors
});`

### Anything else?

Here it is a npm dependencies:
`
{
    "@rainbow-me/rainbowkit": "^1.0.9",
    "@rainbow-me/rainbowkit-siwe-next-auth": "^0.3.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "buffer": "npm:buffer@6.0.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "util": "0.12.4",
    "viem": "^1.7.0",
    "wagmi": "^1.3.10",
    "web-vitals": "^2.1.4"
  }`

![image](https://github.com/rainbow-me/rainbowkit/assets/74368493/55ca335e-36cf-4685-8cee-6fedddad428c)
![image](https://github.com/rainbow-me/rainbowkit/assets/74368493/e7eb1a6e-cc5e-4706-9242-2ce714626ac2)

**Comment by arsen39** [comment]
The issue was addressed with a rather specific solution. In my case, modifications to the package.json file resolved the problem:
`
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
`

I'm not entirely convinced that this solution isn't a workaround, but it appears less makeshift than performing an npm eject and altering webpack configurations.

**Comment by DanielSinclair** [comment]
@arsen39 This is a tough one to diagnose and is likely related to the project configuration. Can you create a minimal reproduction that mirrors your project setup and share on CodeSandbox? That would be super helpful in the debugging process!

**Comment by DanielSinclair** [comment]
@arsen39 Are you able to provide a minimal code sample?

**Comment by DanielSinclair** [comment]
Closing due to inactivity. I presume this was fixed upstream in Wagmi and Viem already.
