### ISSUE TITLE
[bug] "connectorsForWallets" not working for rainbowKit (wagmi v2) in NextJs project

### ISSUE THREAD

**Issue by linghuccc** [rainbow-me/rainbowkit#1824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

2.5.7

### Current Behavior

When "const connectors = connectorsForWallets()" is used, below error will be reported:
`TypeError: (0 , _rainbow_me_rainbowkit__WEBPACK_IMPORTED_MODULE_0__.connectorsForWallets) is not a function
    at eval (webpack-internal:///(rsc)/./src/rainbowkit.ts:15:96)
    at (rsc)/./src/rainbowkit.ts (/home/richard/erc721c/rainbowkit/.next/server/app/page.js:415:1)
    at __webpack_require__ (/home/richard/erc721c/rainbowkit/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/providers.tsx:11:69)
    at (rsc)/./src/app/providers.tsx (/home/richard/erc721c/rainbowkit/.next/server/app/page.js:404:1)
    at __webpack_require__ (/home/richard/erc721c/rainbowkit/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:11:68)
    at (rsc)/./src/app/layout.tsx (/home/richard/erc721c/rainbowkit/.next/server/app/page.js:382:1)
    at Function.__webpack_require__ (/home/richard/erc721c/rainbowkit/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async eB (/home/richard/erc721c/rainbowkit/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:402484)
    at async tt (/home/richard/erc721c/rainbowkit/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406237)
    at async tr (/home/richard/erc721c/rainbowkit/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406787)
    at async tl (/home/richard/erc721c/rainbowkit/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2057)
    at async /home/richard/erc721c/rainbowkit/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2596 {
  digest: '1050920710'`

### Expected Behavior

working without error

### Steps To Reproduce

Step 1:
Initialize project by running "npx create-next-app@latest"

Step 2:
Install rainbowkit (with wagmi v2) by running "npm i @rainbow-me/rainbowkit wagmi viem@2.x @tanstack/react-query"

Step 3:
Update NextJS project configuration file `next.config.mjs` to be
`const nextConfig = {
reactStrictMode: true,
webpack: (config) => {
config.resolve.fallback = { fs: false, net: false, tls: false };
config.externals.push('pino-pretty', 'lokijs', 'encoding')
return config
},
}

Step 4:
Edit file "layout.tsx", add file "provider.tsx"

Step 5:
Run command "npm run dev"

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/linghuccc/rainbowkit/main

**Comment by KosmosKey** [comment]
@linghuccc Please add `'use client';` on top of your `Provider.tsx` component and add `ssr: true` to the `createConfig` wagmi's function. 

+ you'll need to update your `layout.tsx` to this:

```
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={inter.className}>{children}</body>
			</Providers>
		</html>
	)
}
```

Please have a look at our next.js app router example [here](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-app/app)

**Comment by KosmosKey** [comment]
@linghuccc Going to close this issue for now. It should be pretty straight forward, but let me know if you're still facing this issue. [Here](https://github.com/rainbow-me/rainbowkit/issues/1777) is another issue that's very similar due to how next.js app router (server components & client components) works.

**Comment by linghuccc** [comment]
Thanks for your prompt reply. You are the best, man!
