### ISSUE TITLE
[bug] it doesnt work

### ISSUE THREAD

**Issue by vicglarson** [rainbow-me/rainbowkit#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.1

### wagmi Version

0.6.0

### Current Behavior

npm init @rainbow-me/rainbowkit@latest
npm run dev

npm run dev

> my-rainbowkit-app@0.1.0 dev
> next dev

warn  - Invalid casing detected for project dir, received c:\work\crypt\huy\my-rainbowkit-app actual path C:\work\crypt\huy\my-rainbowkit-app, see more info here https://nextjs.org/docs/messages/invalid-project-dir-casing
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - ./node_modules/next/dist/lib/is-error.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\lib\is-error.js
    Used by 3 module(s), i. e.
    c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!C:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\client\index.js
* c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\lib\is-error.js
    Used by 2 module(s), i. e.
    c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\client\router.js

./node_modules/tslib/tslib.es6.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\work\crypt\huy\my-rainbowkit-app\node_modules\tslib\tslib.es6.js
    Used by 10 module(s), i. e.
    C:\work\crypt\huy\my-rainbowkit-app\node_modules\react-remove-scroll\dist\es2015\Combination.js
* c:\work\crypt\huy\my-rainbowkit-app\node_modules\tslib\tslib.es6.js
    Used by 1 module(s), i. e.
    c:\work\crypt\huy\my-rainbowkit-app\node_modules\@swc\helpers\lib\_ts_generator.js

./node_modules/next/dist/client/add-base-path.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!C:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\client\add-base-path.js
    Used by 3 module(s), i. e.
    c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!C:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\client\page-loader.js
* c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\client\add-base-path.js
    Used by 2 module(s), i. e.
    c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\compiled\@next\react-refresh-utils\dist\loader.js!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\shared\lib\router\router.js

for build

Import trace for requested module:
./node_modules/next/dist/client/index.js
./node_modules/next/dist/client/next.js

info  - Collecting page data
[    ] info  - Generating static pages (0/3)TypeError: Cannot read properties of null (reading 'useEffect')
    at exports.useEffect (C:\work\crypt\huy\my-rainbowkit-app\node_modules\react\cjs\react.production.min.js:24:292)
    at QueryClientProvider (C:\work\crypt\huy\my-rainbowkit-app\node_modules\@tanstack\react-query\build\cjs\react-query\src\QueryClientProvider.js:79:20)
    at Wc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:74:209)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useEffect')
    at exports.useEffect (C:\work\crypt\huy\my-rainbowkit-app\node_modules\react\cjs\react.production.min.js:24:292)
    at QueryClientProvider (C:\work\crypt\huy\my-rainbowkit-app\node_modules\@tanstack\react-query\build\cjs\react-query\src\QueryClientProvider.js:79:20)
    at Wc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:74:209)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
TypeError: Cannot read properties of null (reading 'useEffect')
    at exports.useEffect (C:\work\crypt\huy\my-rainbowkit-app\node_modules\react\cjs\react.production.min.js:24:292)
    at QueryClientProvider (C:\work\crypt\huy\my-rainbowkit-app\node_modules\@tanstack\react-query\build\cjs\react-query\src\QueryClientProvider.js:79:20)
    at Wc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:74:209)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useEffect')
    at exports.useEffect (C:\work\crypt\huy\my-rainbowkit-app\node_modules\react\cjs\react.production.min.js:24:292)
    at QueryClientProvider (C:\work\crypt\huy\my-rainbowkit-app\node_modules\@tanstack\react-query\build\cjs\react-query\src\QueryClientProvider.js:79:20)
    at Wc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:74:209)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
TypeError: Cannot read properties of null (reading 'useEffect')
    at exports.useEffect (C:\work\crypt\huy\my-rainbowkit-app\node_modules\react\cjs\react.production.min.js:24:292)
    at QueryClientProvider (C:\work\crypt\huy\my-rainbowkit-app\node_modules\@tanstack\react-query\build\cjs\react-query\src\QueryClientProvider.js:79:20)
    at Wc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:74:209)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (c:\work\crypt\huy\my-rainbowkit-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /_error: /404
        /_error: /500
    at c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\export\index.js:394:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\trace\trace.js:79:20)
    at async c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\index.js:1168:21
    at async Span.traceAsyncFn (c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\trace\trace.js:79:20)
    at async c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\index.js:1044:17
    at async Span.traceAsyncFn (c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\trace\trace.js:79:20)
    at async Object.build [as default] (c:\work\crypt\huy\my-rainbowkit-app\node_modules\next\dist\build\index.js:65:29)

### Expected Behavior

something working
plz note 

### Steps To Reproduce

npm init @rainbow-me/rainbowkit@latest
npm run dev
or npm run build

i use perhaps rancid node 18.0.9 on win 10

### Anything else?

plz note: There are multiple modules with names that only differ in casing. - absolutely wrong phrase for case-insensitve fs.

**Comment by markdalgleish** [comment]
This doesn't seem specific to RainbowKit. Do you see similar issues when [setting up a new Next.js project?](https://nextjs.org/docs#automatic-setup)
